CREATE TABLE items (
    A SERIAL PRIMARY KEY,
    B VARCHAR(100) NOT NULL,
    C TEXT,
    D INTEGER DEFAULT 0,
    E BOOLEAN DEFAULT FALSE,
    F TIMESTAMP DEFAULT NOW(),
    G VARCHAR(50)
);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id VARCHAR(50) NOT NULL
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    price INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    user_id VARCHAR(50) NOT NULL
);
